import * as pdfjsLib from "./vendor/pdfjs/pdf.mjs";

pdfjsLib.GlobalWorkerOptions.workerSrc = new URL(
  "./vendor/pdfjs/pdf.worker.mjs",
  import.meta.url
).toString();

const translations = {
  tr: {
    brandSubtitle: "Profesyonel HTML → PDF",
    language: "Dil",
    accentColor: "Renk",
    darkTheme: "Koyu tema",
    lightTheme: "Açık tema",
    stepOne: "1 · KAYNAK",
    sourceTitle: "HTML içeriği",
    htmlFile: "HTML dosyası",
    htmlCode: "HTML kodu",
    selectFile: "HTML dosyası seç",
    relativeAssets: "CSS, görsel ve font bağlantıları korunur",
    selectedFile: "Dosya hazır",
    browse: "Gözat",
    stepTwo: "2 · AYARLAR",
    pdfSettings: "PDF ayarları",
    reset: "Sıfırla",
    paper: "Kağıt",
    orientation: "Yön",
    portrait: "Dikey",
    landscape: "Yatay",
    scale: "Ölçek",
    margins: "Kenar boşlukları (mm)",
    top: "Üst",
    right: "Sağ",
    bottom: "Alt",
    left: "Sol",
    printBackground: "Arka planları yazdır",
    printBackgroundHint: "Renk ve görselleri PDF’ye dahil eder",
    headerFooter: "Üst/alt bilgi",
    headerFooterHint: "Başlık ve sayfa numarası ekler",
    preview: "Önizle",
    createPdf: "PDF oluştur",
    cancel: "İptal",
    liveOutput: "GERÇEK ÇIKTI",
    previewTitle: "PDF önizleme",
    emptyTitle: "PDF’niz burada görünecek",
    emptyBody: "Bir HTML dosyası seçin veya kodunuzu yapıştırın, ardından Önizle’ye basın.",
    rendering: "PDF hazırlanıyor…",
    renderingHint: "Fontlar ve görseller yükleniyor",
    ready: "Hazır",
    fileRequired: "Önce bir HTML dosyası seçin.",
    codeRequired: "HTML kodu boş olamaz.",
    previewReady: "Gerçek PDF önizlemesi hazır.",
    previewOutdated: "Ayarlar değişti; önizleme güncelleniyor…",
    saved: "PDF kaydedildi:",
    canceled: "İşlem iptal edildi.",
    error: "İşlem tamamlanamadı:",
    pages: "{count} sayfa",
    page: "Sayfa {number}",
    settingsReset: "PDF ayarları sıfırlandı."
  },
  en: {
    brandSubtitle: "Professional HTML → PDF",
    language: "Language",
    accentColor: "Color",
    darkTheme: "Dark theme",
    lightTheme: "Light theme",
    stepOne: "1 · SOURCE",
    sourceTitle: "HTML content",
    htmlFile: "HTML file",
    htmlCode: "HTML code",
    selectFile: "Select an HTML file",
    relativeAssets: "Relative CSS, images and fonts are preserved",
    selectedFile: "File ready",
    browse: "Browse",
    stepTwo: "2 · SETTINGS",
    pdfSettings: "PDF settings",
    reset: "Reset",
    paper: "Paper",
    orientation: "Orientation",
    portrait: "Portrait",
    landscape: "Landscape",
    scale: "Scale",
    margins: "Margins (mm)",
    top: "Top",
    right: "Right",
    bottom: "Bottom",
    left: "Left",
    printBackground: "Print backgrounds",
    printBackgroundHint: "Includes colors and images in the PDF",
    headerFooter: "Header/footer",
    headerFooterHint: "Adds the title and page number",
    preview: "Preview",
    createPdf: "Create PDF",
    cancel: "Cancel",
    liveOutput: "ACTUAL OUTPUT",
    previewTitle: "PDF preview",
    emptyTitle: "Your PDF will appear here",
    emptyBody: "Select an HTML file or paste your code, then choose Preview.",
    rendering: "Preparing PDF…",
    renderingHint: "Loading fonts and images",
    ready: "Ready",
    fileRequired: "Select an HTML file first.",
    codeRequired: "HTML code cannot be empty.",
    previewReady: "Actual PDF preview is ready.",
    previewOutdated: "Settings changed; updating the preview…",
    saved: "PDF saved:",
    canceled: "Operation cancelled.",
    error: "The operation could not be completed:",
    pages: "{count} pages",
    page: "Page {number}",
    settingsReset: "PDF settings were reset."
  }
};

const sampleHtml = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>WebPDF Studio Sample</title>
  <style>
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: Inter, Arial, sans-serif;
      color: #172033;
      background: #f4f7fb;
    }
    .document {
      max-width: 760px;
      margin: 36px auto;
      padding: 44px;
      background: white;
      border-radius: 18px;
      box-shadow: 0 20px 55px rgba(15, 23, 42, .12);
    }
    .badge {
      display: inline-block;
      padding: 7px 11px;
      color: #1d4ed8;
      background: #dbeafe;
      border-radius: 999px;
      font-weight: 700;
      font-size: 12px;
    }
    h1 { margin: 18px 0 8px; font-size: 38px; }
    p { color: #58677d; line-height: 1.7; }
    .grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 14px;
      margin-top: 28px;
    }
    .card {
      padding: 18px;
      border: 1px solid #dce3ec;
      border-radius: 12px;
    }
  </style>
</head>
<body>
  <main class="document">
    <span class="badge">WebPDF Studio</span>
    <h1>Pixel-perfect PDF output</h1>
    <p>
      This sample uses modern HTML and CSS. Preview shows the exact PDF
      pages generated by Chromium.
    </p>
    <section class="grid">
      <div class="card"><strong>Cross-platform</strong><p>Windows, macOS and Linux.</p></div>
      <div class="card"><strong>Accurate</strong><p>One engine for preview and export.</p></div>
    </section>
  </main>
</body>
</html>`;

const elements = {
  languageSelect: document.querySelector("#languageSelect"),
  accentPicker: document.querySelector("#accentPicker"),
  themeButton: document.querySelector("#themeButton"),
  themeIcon: document.querySelector("#themeIcon"),
  themeLabel: document.querySelector("#themeLabel"),
  platformBadge: document.querySelector("#platformBadge"),
  modeTabs: [...document.querySelectorAll(".mode-tab")],
  filePane: document.querySelector("#filePane"),
  codePane: document.querySelector("#codePane"),
  selectFileButton: document.querySelector("#selectFileButton"),
  fileCardTitle: document.querySelector("#fileCardTitle"),
  selectedFilePath: document.querySelector("#selectedFilePath"),
  htmlEditor: document.querySelector("#htmlEditor"),
  pageSize: document.querySelector("#pageSize"),
  orientation: document.querySelector("#orientation"),
  scale: document.querySelector("#scale"),
  marginTop: document.querySelector("#marginTop"),
  marginRight: document.querySelector("#marginRight"),
  marginBottom: document.querySelector("#marginBottom"),
  marginLeft: document.querySelector("#marginLeft"),
  printBackground: document.querySelector("#printBackground"),
  headerFooter: document.querySelector("#headerFooter"),
  resetSettingsButton: document.querySelector("#resetSettingsButton"),
  previewButton: document.querySelector("#previewButton"),
  saveButton: document.querySelector("#saveButton"),
  cancelButton: document.querySelector("#cancelButton"),
  previewViewport: document.querySelector("#previewViewport"),
  emptyState: document.querySelector("#emptyState"),
  loadingState: document.querySelector("#loadingState"),
  pdfPages: document.querySelector("#pdfPages"),
  pageCount: document.querySelector("#pageCount"),
  pdfSize: document.querySelector("#pdfSize"),
  statusDot: document.querySelector("#statusDot"),
  statusText: document.querySelector("#statusText"),
  engineText: document.querySelector("#engineText")
};

const state = {
  mode: "file",
  selectedFile: null,
  language: "tr",
  theme: "light",
  accent: "#2563eb",
  busy: false,
  previewAvailable: false,
  previewDirty: false,
  pendingPreview: false,
  previewTimer: null,
  pageCount: 0,
  operationId: 0,
  renderGeneration: 0,
  activePdfJob: null
};
let preferenceSaveQueue = Promise.resolve();

function t(key, replacements = {}) {
  let text = translations[state.language][key] ?? key;
  for (const [name, value] of Object.entries(replacements)) {
    text = text.replace(`{${name}}`, value);
  }
  return text;
}

function hexToRgb(hex) {
  const value = hex.replace("#", "");
  return [
    Number.parseInt(value.slice(0, 2), 16),
    Number.parseInt(value.slice(2, 4), 16),
    Number.parseInt(value.slice(4, 6), 16)
  ].join(", ");
}

function applyAppearance() {
  document.documentElement.lang = state.language;
  document.documentElement.dataset.theme = state.theme;
  document.documentElement.style.setProperty("--accent", state.accent);
  document.documentElement.style.setProperty(
    "--accent-rgb",
    hexToRgb(state.accent)
  );
  elements.languageSelect.value = state.language;
  elements.accentPicker.value = state.accent;
  elements.themeIcon.textContent = state.theme === "dark" ? "☀" : "☾";
  elements.themeLabel.dataset.i18n = state.theme === "dark"
    ? "lightTheme"
    : "darkTheme";

  for (const element of document.querySelectorAll("[data-i18n]")) {
    element.textContent = t(element.dataset.i18n);
  }

  if (state.selectedFile) {
    elements.fileCardTitle.textContent = t("selectedFile");
    elements.selectedFilePath.textContent = state.selectedFile.filePath;
  }

  if (state.pageCount > 0) {
    elements.pageCount.textContent = t("pages", { count: state.pageCount });
    for (const [index, label] of [
      ...elements.pdfPages.querySelectorAll(".page-label")
    ].entries()) {
      label.textContent = t("page", { number: index + 1 });
    }
  }
}

function persistAppearance() {
  const preferences = {
    language: state.language,
    theme: state.theme,
    accent: state.accent
  };
  preferenceSaveQueue = preferenceSaveQueue
    .catch(() => {})
    .then(() => window.webPdf.savePreferences(preferences));
  return preferenceSaveQueue;
}

function setMode(mode) {
  const changed = state.mode !== mode;
  state.mode = mode;
  for (const tab of elements.modeTabs) {
    const active = tab.dataset.mode === mode;
    tab.classList.toggle("active", active);
    tab.setAttribute("aria-selected", String(active));
  }
  elements.filePane.classList.toggle("active", mode === "file");
  elements.codePane.classList.toggle("active", mode === "code");
  if (changed) {
    markPreviewDirty();
  }
}

function setStatus(message, type = "ready") {
  elements.statusText.textContent = message;
  elements.statusDot.classList.toggle("busy", type === "busy");
  elements.statusDot.classList.toggle("error", type === "error");
}

function setBusy(busy) {
  state.busy = busy;
  elements.previewButton.disabled = busy;
  elements.saveButton.disabled = busy;
  elements.cancelButton.classList.toggle("hidden", !busy);
  if (busy) {
    elements.emptyState.classList.add("hidden");
    elements.pdfPages.classList.add("hidden");
    elements.loadingState.classList.remove("hidden");
    setStatus(t("rendering"), "busy");
  } else {
    elements.loadingState.classList.add("hidden");
    elements.emptyState.classList.toggle("hidden", state.previewAvailable);
    elements.pdfPages.classList.toggle("hidden", !state.previewAvailable);
  }
}

function buildRequest() {
  if (state.mode === "file" && !state.selectedFile) {
    throw new Error(t("fileRequired"));
  }
  if (state.mode === "code" && !elements.htmlEditor.value.trim()) {
    throw new Error(t("codeRequired"));
  }

  return {
    mode: state.mode,
    language: state.language,
    filePath: state.selectedFile?.filePath ?? "",
    htmlSource: elements.htmlEditor.value,
    pageSize: elements.pageSize.value,
    landscape: elements.orientation.value === "landscape",
    scale: Number(elements.scale.value),
    margins: {
      top: Number(elements.marginTop.value),
      right: Number(elements.marginRight.value),
      bottom: Number(elements.marginBottom.value),
      left: Number(elements.marginLeft.value)
    },
    printBackground: elements.printBackground.checked,
    displayHeaderFooter: elements.headerFooter.checked
  };
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

function getCurrentRequestKey() {
  try {
    return JSON.stringify(buildRequest());
  } catch {
    return "";
  }
}

function clearScheduledPreview() {
  if (!state.previewTimer) {
    return;
  }
  clearTimeout(state.previewTimer);
  state.previewTimer = null;
}

function isCancellationError(error) {
  const name = String(error?.name ?? "");
  const message = String(error?.message ?? "").toLowerCase();
  return name === "RenderingCancelledException" || message.includes("cancel");
}

function destroyPdfJob(job) {
  if (!job) {
    return Promise.resolve();
  }

  if (job.renderTask) {
    try {
      job.renderTask.cancel();
    } catch {
      // The render may already have completed.
    }
  }

  if (!job.destroyPromise) {
    job.destroyPromise = Promise.resolve().then(() => job.loadingTask.destroy());
  }
  return job.destroyPromise;
}

function invalidatePdfRendering() {
  state.renderGeneration += 1;
  if (state.activePdfJob) {
    void destroyPdfJob(state.activePdfJob).catch(() => {});
  }
}

function schedulePreviewRefresh(delay = 450) {
  clearScheduledPreview();
  state.previewTimer = setTimeout(() => {
    state.previewTimer = null;
    if (state.busy) {
      state.pendingPreview = true;
      return;
    }
    void previewPdf({ automatic: true });
  }, delay);
}

function markPreviewDirty() {
  invalidatePdfRendering();
  if (state.busy) {
    state.pendingPreview = true;
  }
  if (!state.previewAvailable) {
    return;
  }
  state.previewDirty = true;
  setStatus(t("previewOutdated"), "busy");
  schedulePreviewRefresh();
}

async function renderPdfPages(rawBytes, renderGeneration) {
  const bytes = rawBytes instanceof Uint8Array
    ? rawBytes
    : new Uint8Array(rawBytes);
  const previousJob = state.activePdfJob;
  if (previousJob) {
    try {
      await destroyPdfJob(previousJob);
    } catch (error) {
      if (
        renderGeneration === state.renderGeneration &&
        !isCancellationError(error)
      ) {
        throw error;
      }
    }
  }
  if (renderGeneration !== state.renderGeneration) {
    return false;
  }

  const job = {
    loadingTask: pdfjsLib.getDocument({ data: bytes }),
    renderTask: null,
    destroyPromise: null
  };
  state.activePdfJob = job;

  try {
    const pdfDocument = await job.loadingTask.promise;
    if (renderGeneration !== state.renderGeneration) {
      return false;
    }

    const availableWidth = Math.max(
      320,
      elements.previewViewport.clientWidth - 72
    );
    const pageFragment = document.createDocumentFragment();
    const pageLabels = [];

    for (
      let pageNumber = 1;
      pageNumber <= pdfDocument.numPages;
      pageNumber += 1
    ) {
      if (renderGeneration !== state.renderGeneration) {
        return false;
      }

      const pdfPage = await pdfDocument.getPage(pageNumber);
      if (renderGeneration !== state.renderGeneration) {
        return false;
      }

      const baseViewport = pdfPage.getViewport({ scale: 1 });
      const cssScale = Math.min(1.35, availableWidth / baseViewport.width);
      const outputScale = Math.min(window.devicePixelRatio || 1, 2);
      const renderViewport = pdfPage.getViewport({
        scale: cssScale * outputScale
      });
      const pageContainer = document.createElement("article");
      const canvas = document.createElement("canvas");
      const label = document.createElement("span");
      const context = canvas.getContext("2d", { alpha: false });

      pageContainer.className = "pdf-page";
      label.className = "page-label";
      canvas.width = Math.floor(renderViewport.width);
      canvas.height = Math.floor(renderViewport.height);
      canvas.style.width = `${Math.floor(renderViewport.width / outputScale)}px`;
      canvas.style.height = `${Math.floor(renderViewport.height / outputScale)}px`;
      pageContainer.append(canvas, label);
      pageFragment.append(pageContainer);
      pageLabels.push(label);

      job.renderTask = pdfPage.render({
        canvasContext: context,
        viewport: renderViewport,
        background: "#ffffff"
      });
      await job.renderTask.promise;
      job.renderTask = null;
    }

    if (renderGeneration !== state.renderGeneration) {
      return false;
    }

    for (const [index, label] of pageLabels.entries()) {
      label.textContent = t("page", { number: index + 1 });
    }
    elements.pdfPages.replaceChildren(pageFragment);
    elements.pageCount.textContent = t("pages", {
      count: pdfDocument.numPages
    });
    state.pageCount = pdfDocument.numPages;
    elements.emptyState.classList.add("hidden");
    elements.pdfPages.classList.remove("hidden");
    return true;
  } catch (error) {
    if (
      renderGeneration !== state.renderGeneration ||
      isCancellationError(error)
    ) {
      return false;
    }
    throw error;
  } finally {
    await destroyPdfJob(job);
    if (state.activePdfJob === job) {
      state.activePdfJob = null;
    }
  }
}

async function previewPdf({ automatic = false } = {}) {
  if (state.busy) {
    state.pendingPreview = true;
    return;
  }

  let request;
  try {
    request = buildRequest();
  } catch (error) {
    state.pendingPreview = false;
    state.previewDirty = state.previewAvailable;
    clearScheduledPreview();
    setStatus(`${t("error")} ${error.message}`, "error");
    return;
  }

  const requestKey = JSON.stringify(request);
  const operationId = ++state.operationId;
  const renderGeneration = state.renderGeneration;
  state.pendingPreview = false;
  try {
    setBusy(true);
    const result = await window.webPdf.generatePreview(request);
    if (operationId !== state.operationId) {
      return;
    }
    if (getCurrentRequestKey() !== requestKey) {
      state.pendingPreview = true;
      return;
    }
    const rendered = await renderPdfPages(result.bytes, renderGeneration);
    if (operationId !== state.operationId) {
      return;
    }
    if (
      !rendered ||
      renderGeneration !== state.renderGeneration ||
      getCurrentRequestKey() !== requestKey
    ) {
      state.pendingPreview = true;
      return;
    }
    elements.pdfSize.textContent = formatBytes(result.size);
    state.previewAvailable = true;
    state.previewDirty = false;
    setStatus(t("previewReady"));
  } catch (error) {
    if (operationId === state.operationId && !isCancellationError(error)) {
      setStatus(`${t("error")} ${error.message}`, "error");
    }
  } finally {
    if (operationId === state.operationId) {
      setBusy(false);
      if (state.pendingPreview) {
        schedulePreviewRefresh(50);
      }
    }
  }
}

async function savePdf() {
  let request;
  let operationId;
  let renderGeneration;
  try {
    request = buildRequest();
    operationId = ++state.operationId;
    renderGeneration = state.renderGeneration;
    setBusy(true);
    const result = await window.webPdf.savePdf(request);
    if (operationId !== state.operationId) {
      return;
    }
    if (result.canceled) {
      setStatus(t("canceled"));
      return;
    }
    const rendered = await renderPdfPages(result.bytes, renderGeneration);
    if (
      rendered &&
      operationId === state.operationId &&
      renderGeneration === state.renderGeneration
    ) {
      elements.pdfSize.textContent = formatBytes(result.size);
      state.previewAvailable = true;
      state.previewDirty = false;
    }
    if (operationId !== state.operationId) {
      return;
    }
    setStatus(`${t("saved")} ${result.filePath}`);
  } catch (error) {
    if (
      (!operationId || operationId === state.operationId) &&
      !isCancellationError(error)
    ) {
      setStatus(`${t("error")} ${error.message}`, "error");
    }
  } finally {
    if (!operationId || operationId === state.operationId) {
      setBusy(false);
      if (state.pendingPreview) {
        schedulePreviewRefresh(50);
      }
    }
  }
}

function resetPdfSettings() {
  elements.pageSize.value = "A4";
  elements.orientation.value = "portrait";
  elements.scale.value = "1";
  elements.marginTop.value = "12";
  elements.marginRight.value = "12";
  elements.marginBottom.value = "12";
  elements.marginLeft.value = "12";
  elements.printBackground.checked = true;
  elements.headerFooter.checked = false;
  markPreviewDirty();
  if (!state.previewAvailable) {
    setStatus(t("settingsReset"));
  }
}

for (const tab of elements.modeTabs) {
  tab.addEventListener("click", () => setMode(tab.dataset.mode));
}

elements.selectFileButton.addEventListener("click", async () => {
  const selectedFile = await window.webPdf.selectHtmlFile(state.language);
  if (!selectedFile) return;
  state.selectedFile = selectedFile;
  applyAppearance();
  setStatus(selectedFile.filePath);
  markPreviewDirty();
});

elements.languageSelect.addEventListener("change", async () => {
  state.language = elements.languageSelect.value;
  applyAppearance();
  if (state.previewDirty) {
    setStatus(t("previewOutdated"), "busy");
  } else if (state.previewAvailable) {
    setStatus(t("previewReady"));
  } else {
    setStatus(t("ready"));
  }
  await persistAppearance();
});

elements.accentPicker.addEventListener("input", () => {
  state.accent = elements.accentPicker.value;
  applyAppearance();
});

elements.accentPicker.addEventListener("change", persistAppearance);

elements.themeButton.addEventListener("click", async () => {
  state.theme = state.theme === "dark" ? "light" : "dark";
  applyAppearance();
  await persistAppearance();
});

const pdfSettingElements = [
  elements.pageSize,
  elements.orientation,
  elements.scale,
  elements.marginTop,
  elements.marginRight,
  elements.marginBottom,
  elements.marginLeft,
  elements.printBackground,
  elements.headerFooter
];
for (const element of pdfSettingElements) {
  element.addEventListener("input", markPreviewDirty);
  element.addEventListener("change", markPreviewDirty);
}
elements.htmlEditor.addEventListener("input", markPreviewDirty);

elements.resetSettingsButton.addEventListener("click", resetPdfSettings);
elements.previewButton.addEventListener("click", previewPdf);
elements.saveButton.addEventListener("click", savePdf);
elements.cancelButton.addEventListener("click", async () => {
  state.operationId += 1;
  state.pendingPreview = false;
  clearScheduledPreview();
  invalidatePdfRendering();
  try {
    await window.webPdf.cancelOperation();
  } finally {
    setBusy(false);
    setStatus(t("canceled"));
  }
});

async function initialize() {
  elements.htmlEditor.value = sampleHtml;
  const [preferences, platformInfo] = await Promise.all([
    window.webPdf.loadPreferences(),
    window.webPdf.platformInfo()
  ]);
  state.language = preferences.language;
  state.theme = preferences.theme;
  state.accent = preferences.accent;
  const platformNames = {
    win32: "Windows",
    darwin: "macOS",
    linux: "Linux"
  };
  elements.platformBadge.textContent =
    `${platformNames[platformInfo.platform] ?? platformInfo.platform} · V${platformInfo.version}`;
  elements.engineText.textContent = "Chromium PDF Engine";
  applyAppearance();
  if (new URLSearchParams(window.location.search).has("preview")) {
    setMode("code");
    await previewPdf();
  } else {
    setMode("file");
  }
}

await initialize();
