import * as pdfjsLib from "./vendor/pdfjs/pdf.mjs";

pdfjsLib.GlobalWorkerOptions.workerSrc = new URL(
  "./vendor/pdfjs/pdf.worker.mjs",
  import.meta.url
).toString();

const translations = {
  tr: {
    brandSubtitle: "Profesyonel HTML → PDF",
    language: "Dil",
    accentColor: "Renk",
    darkTheme: "Koyu tema",
    lightTheme: "Açık tema",
    stepOne: "1 · KAYNAK",
    sourceTitle: "HTML içeriği",
    htmlFile: "HTML dosyası",
    htmlCode: "HTML kodu",
    selectFile: "HTML dosyası seç",
    relativeAssets: "CSS, görsel ve font bağlantıları korunur",
    selectedFile: "Dosya hazır",
    browse: "Gözat",
    stepTwo: "2 · AYARLAR",
    pdfSettings: "PDF ayarları",
    reset: "Sıfırla",
    paper: "Kağıt",
    orientation: "Yön",
    portrait: "Dikey",
    landscape: "Yatay",
    scale: "Ölçek",
    margins: "Kenar boşlukları (mm)",
    top: "Üst",
    right: "Sağ",
    bottom: "Alt",
    left: "Sol",
    printBackground: "Arka planları yazdır",
    printBackgroundHint: "Renk ve görselleri PDF’ye dahil eder",
    headerFooter: "Üst/alt bilgi",
    headerFooterHint: "Başlık ve sayfa numarası ekler",
    preview: "Önizle",
    createPdf: "PDF oluştur",
    cancel: "İptal",
    liveOutput: "GERÇEK ÇIKTI",
    previewTitle: "PDF önizleme",
    emptyTitle: "PDF’niz burada görünecek",
    emptyBody: "Bir HTML dosyası seçin veya kodunuzu yapıştırın, ardından Önizle’ye basın.",
    rendering: "PDF hazırlanıyor…",
    renderingHint: "Fontlar ve görseller yükleniyor",
    ready: "Hazır",
    fileRequired: "Önce bir HTML dosyası seçin.",
    codeRequired: "HTML kodu boş olamaz.",
    previewReady: "Gerçek PDF önizlemesi hazır.",
    saved: "PDF kaydedildi:",
    canceled: "İşlem iptal edildi.",
    error: "İşlem tamamlanamadı:",
    pages: "{count} sayfa",
    page: "Sayfa {number}",
    settingsReset: "PDF ayarları sıfırlandı."
  },
  en: {
    brandSubtitle: "Professional HTML → PDF",
    language: "Language",
    accentColor: "Color",
    darkTheme: "Dark theme",
    lightTheme: "Light theme",
    stepOne: "1 · SOURCE",
    sourceTitle: "HTML content",
    htmlFile: "HTML file",
    htmlCode: "HTML code",
    selectFile: "Select an HTML file",
    relativeAssets: "Relative CSS, images and fonts are preserved",
    selectedFile: "File ready",
    browse: "Browse",
    stepTwo: "2 · SETTINGS",
    pdfSettings: "PDF settings",
    reset: "Reset",
    paper: "Paper",
    orientation: "Orientation",
    portrait: "Portrait",
    landscape: "Landscape",
    scale: "Scale",
    margins: "Margins (mm)",
    top: "Top",
    right: "Right",
    bottom: "Bottom",
    left: "Left",
    printBackground: "Print backgrounds",
    printBackgroundHint: "Includes colors and images in the PDF",
    headerFooter: "Header/footer",
    headerFooterHint: "Adds the title and page number",
    preview: "Preview",
    createPdf: "Create PDF",
    cancel: "Cancel",
    liveOutput: "ACTUAL OUTPUT",
    previewTitle: "PDF preview",
    emptyTitle: "Your PDF will appear here",
    emptyBody: "Select an HTML file or paste your code, then choose Preview.",
    rendering: "Preparing PDF…",
    renderingHint: "Loading fonts and images",
    ready: "Ready",
    fileRequired: "Select an HTML file first.",
    codeRequired: "HTML code cannot be empty.",
    previewReady: "Actual PDF preview is ready.",
    saved: "PDF saved:",
    canceled: "Operation cancelled.",
    error: "The operation could not be completed:",
    pages: "{count} pages",
    page: "Page {number}",
    settingsReset: "PDF settings were reset."
  }
};

const sampleHtml = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>WebPDF Studio Sample</title>
  <style>
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: Inter, Arial, sans-serif;
      color: #172033;
      background: #f4f7fb;
    }
    .document {
      max-width: 760px;
      margin: 36px auto;
      padding: 44px;
      background: white;
      border-radius: 18px;
      box-shadow: 0 20px 55px rgba(15, 23, 42, .12);
    }
    .badge {
      display: inline-block;
      padding: 7px 11px;
      color: #1d4ed8;
      background: #dbeafe;
      border-radius: 999px;
      font-weight: 700;
      font-size: 12px;
    }
    h1 { margin: 18px 0 8px; font-size: 38px; }
    p { color: #58677d; line-height: 1.7; }
    .grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 14px;
      margin-top: 28px;
    }
    .card {
      padding: 18px;
      border: 1px solid #dce3ec;
      border-radius: 12px;
    }
  </style>
</head>
<body>
  <main class="document">
    <span class="badge">WebPDF Studio</span>
    <h1>Pixel-perfect PDF output</h1>
    <p>
      This sample uses modern HTML and CSS. Preview shows the exact PDF
      pages generated by Chromium.
    </p>
    <section class="grid">
      <div class="card"><strong>Cross-platform</strong><p>Windows, macOS and Linux.</p></div>
      <div class="card"><strong>Accurate</strong><p>One engine for preview and export.</p></div>
    </section>
  </main>
</body>
</html>`;

const elements = {
  languageSelect: document.querySelector("#languageSelect"),
  accentPicker: document.querySelector("#accentPicker"),
  themeButton: document.querySelector("#themeButton"),
  themeIcon: document.querySelector("#themeIcon"),
  themeLabel: document.querySelector("#themeLabel"),
  platformBadge: document.querySelector("#platformBadge"),
  modeTabs: [...document.querySelectorAll(".mode-tab")],
  filePane: document.querySelector("#filePane"),
  codePane: document.querySelector("#codePane"),
  selectFileButton: document.querySelector("#selectFileButton"),
  fileCardTitle: document.querySelector("#fileCardTitle"),
  selectedFilePath: document.querySelector("#selectedFilePath"),
  htmlEditor: document.querySelector("#htmlEditor"),
  pageSize: document.querySelector("#pageSize"),
  orientation: document.querySelector("#orientation"),
  scale: document.querySelector("#scale"),
  marginTop: document.querySelector("#marginTop"),
  marginRight: document.querySelector("#marginRight"),
  marginBottom: document.querySelector("#marginBottom"),
  marginLeft: document.querySelector("#marginLeft"),
  printBackground: document.querySelector("#printBackground"),
  headerFooter: document.querySelector("#headerFooter"),
  resetSettingsButton: document.querySelector("#resetSettingsButton"),
  previewButton: document.querySelector("#previewButton"),
  saveButton: document.querySelector("#saveButton"),
  cancelButton: document.querySelector("#cancelButton"),
  previewViewport: document.querySelector("#previewViewport"),
  emptyState: document.querySelector("#emptyState"),
  loadingState: document.querySelector("#loadingState"),
  pdfPages: document.querySelector("#pdfPages"),
  pageCount: document.querySelector("#pageCount"),
  pdfSize: document.querySelector("#pdfSize"),
  statusDot: document.querySelector("#statusDot"),
  statusText: document.querySelector("#statusText"),
  engineText: document.querySelector("#engineText")
};

const state = {
  mode: "file",
  selectedFile: null,
  language: "tr",
  theme: "light",
  accent: "#2563eb",
  busy: false
};

function t(key, replacements = {}) {
  let text = translations[state.language][key] ?? key;
  for (const [name, value] of Object.entries(replacements)) {
    text = text.replace(`{${name}}`, value);
  }
  return text;
}

function hexToRgb(hex) {
  const value = hex.replace("#", "");
  return [
    Number.parseInt(value.slice(0, 2), 16),
    Number.parseInt(value.slice(2, 4), 16),
    Number.parseInt(value.slice(4, 6), 16)
  ].join(", ");
}

function applyAppearance() {
  document.documentElement.lang = state.language;
  document.documentElement.dataset.theme = state.theme;
  document.documentElement.style.setProperty("--accent", state.accent);
  document.documentElement.style.setProperty(
    "--accent-rgb",
    hexToRgb(state.accent)
  );
  elements.languageSelect.value = state.language;
  elements.accentPicker.value = state.accent;
  elements.themeIcon.textContent = state.theme === "dark" ? "☀" : "☾";
  elements.themeLabel.dataset.i18n = state.theme === "dark"
    ? "lightTheme"
    : "darkTheme";

  for (const element of document.querySelectorAll("[data-i18n]")) {
    element.textContent = t(element.dataset.i18n);
  }

  if (state.selectedFile) {
    elements.fileCardTitle.textContent = t("selectedFile");
    elements.selectedFilePath.textContent = state.selectedFile.filePath;
  }
}

async function persistAppearance() {
  await window.webPdf.savePreferences({
    language: state.language,
    theme: state.theme,
    accent: state.accent
  });
}

function setMode(mode) {
  state.mode = mode;
  for (const tab of elements.modeTabs) {
    const active = tab.dataset.mode === mode;
    tab.classList.toggle("active", active);
    tab.setAttribute("aria-selected", String(active));
  }
  elements.filePane.classList.toggle("active", mode === "file");
  elements.codePane.classList.toggle("active", mode === "code");
}

function setStatus(message, type = "ready") {
  elements.statusText.textContent = message;
  elements.statusDot.classList.toggle("busy", type === "busy");
  elements.statusDot.classList.toggle("error", type === "error");
}

function setBusy(busy) {
  state.busy = busy;
  elements.previewButton.disabled = busy;
  elements.saveButton.disabled = busy;
  elements.cancelButton.classList.toggle("hidden", !busy);
  if (busy) {
    elements.emptyState.classList.add("hidden");
    elements.pdfPages.classList.add("hidden");
    elements.loadingState.classList.remove("hidden");
    setStatus(t("rendering"), "busy");
  } else {
    elements.loadingState.classList.add("hidden");
  }
}

function buildRequest() {
  if (state.mode === "file" && !state.selectedFile) {
    throw new Error(t("fileRequired"));
  }
  if (state.mode === "code" && !elements.htmlEditor.value.trim()) {
    throw new Error(t("codeRequired"));
  }

  return {
    mode: state.mode,
    filePath: state.selectedFile?.filePath ?? "",
    htmlSource: elements.htmlEditor.value,
    pageSize: elements.pageSize.value,
    landscape: elements.orientation.value === "landscape",
    scale: Number(elements.scale.value),
    margins: {
      top: Number(elements.marginTop.value),
      right: Number(elements.marginRight.value),
      bottom: Number(elements.marginBottom.value),
      left: Number(elements.marginLeft.value)
    },
    printBackground: elements.printBackground.checked,
    displayHeaderFooter: elements.headerFooter.checked
  };
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

async function renderPdfPages(rawBytes) {
  const bytes = rawBytes instanceof Uint8Array
    ? rawBytes
    : new Uint8Array(rawBytes);
  const documentTask = pdfjsLib.getDocument({ data: bytes });
  const pdfDocument = await documentTask.promise;
  elements.pdfPages.replaceChildren();

  const availableWidth = Math.max(
    320,
    elements.previewViewport.clientWidth - 72
  );

  for (let pageNumber = 1; pageNumber <= pdfDocument.numPages; pageNumber += 1) {
    const pdfPage = await pdfDocument.getPage(pageNumber);
    const baseViewport = pdfPage.getViewport({ scale: 1 });
    const cssScale = Math.min(1.35, availableWidth / baseViewport.width);
    const outputScale = Math.min(window.devicePixelRatio || 1, 2);
    const renderViewport = pdfPage.getViewport({
      scale: cssScale * outputScale
    });
    const pageContainer = document.createElement("article");
    const canvas = document.createElement("canvas");
    const label = document.createElement("span");
    const context = canvas.getContext("2d", { alpha: false });

    pageContainer.className = "pdf-page";
    label.className = "page-label";
    label.textContent = t("page", { number: pageNumber });
    canvas.width = Math.floor(renderViewport.width);
    canvas.height = Math.floor(renderViewport.height);
    canvas.style.width = `${Math.floor(renderViewport.width / outputScale)}px`;
    canvas.style.height = `${Math.floor(renderViewport.height / outputScale)}px`;
    pageContainer.append(canvas, label);
    elements.pdfPages.append(pageContainer);

    await pdfPage.render({
      canvasContext: context,
      viewport: renderViewport,
      background: "#ffffff"
    }).promise;
  }

  elements.pageCount.textContent = t("pages", {
    count: pdfDocument.numPages
  });
  elements.emptyState.classList.add("hidden");
  elements.pdfPages.classList.remove("hidden");
}

async function previewPdf() {
  try {
    const request = buildRequest();
    setBusy(true);
    const result = await window.webPdf.generatePreview(request);
    await renderPdfPages(result.bytes);
    elements.pdfSize.textContent = formatBytes(result.size);
    setStatus(t("previewReady"));
  } catch (error) {
    if (!String(error?.message).includes("cancel")) {
      setStatus(`${t("error")} ${error.message}`, "error");
    }
  } finally {
    setBusy(false);
  }
}

async function savePdf() {
  try {
    const request = buildRequest();
    setBusy(true);
    const result = await window.webPdf.savePdf(request);
    if (result.canceled) {
      setStatus(t("canceled"));
      return;
    }
    elements.pdfSize.textContent = formatBytes(result.size);
    setStatus(`${t("saved")} ${result.filePath}`);
  } catch (error) {
    if (!String(error?.message).includes("cancel")) {
      setStatus(`${t("error")} ${error.message}`, "error");
    }
  } finally {
    setBusy(false);
  }
}

function resetPdfSettings() {
  elements.pageSize.value = "A4";
  elements.orientation.value = "portrait";
  elements.scale.value = "1";
  elements.marginTop.value = "12";
  elements.marginRight.value = "12";
  elements.marginBottom.value = "12";
  elements.marginLeft.value = "12";
  elements.printBackground.checked = true;
  elements.headerFooter.checked = false;
  setStatus(t("settingsReset"));
}

for (const tab of elements.modeTabs) {
  tab.addEventListener("click", () => setMode(tab.dataset.mode));
}

elements.selectFileButton.addEventListener("click", async () => {
  const selectedFile = await window.webPdf.selectHtmlFile();
  if (!selectedFile) return;
  state.selectedFile = selectedFile;
  applyAppearance();
  setStatus(selectedFile.filePath);
});

elements.languageSelect.addEventListener("change", async () => {
  state.language = elements.languageSelect.value;
  applyAppearance();
  await persistAppearance();
});

elements.accentPicker.addEventListener("input", () => {
  state.accent = elements.accentPicker.value;
  applyAppearance();
});

elements.accentPicker.addEventListener("change", persistAppearance);

elements.themeButton.addEventListener("click", async () => {
  state.theme = state.theme === "dark" ? "light" : "dark";
  applyAppearance();
  await persistAppearance();
});

elements.resetSettingsButton.addEventListener("click", resetPdfSettings);
elements.previewButton.addEventListener("click", previewPdf);
elements.saveButton.addEventListener("click", savePdf);
elements.cancelButton.addEventListener("click", async () => {
  await window.webPdf.cancelOperation();
  setBusy(false);
  setStatus(t("canceled"));
});

async function initialize() {
  elements.htmlEditor.value = sampleHtml;
  const [preferences, platformInfo] = await Promise.all([
    window.webPdf.loadPreferences(),
    window.webPdf.platformInfo()
  ]);
  state.language = preferences.language;
  state.theme = preferences.theme;
  state.accent = preferences.accent;
  const platformNames = {
    win32: "Windows",
    darwin: "macOS",
    linux: "Linux"
  };
  elements.platformBadge.textContent =
    `${platformNames[platformInfo.platform] ?? platformInfo.platform} · V${platformInfo.version}`;
  elements.engineText.textContent = "Chromium PDF Engine";
  applyAppearance();
  if (new URLSearchParams(window.location.search).has("preview")) {
    setMode("code");
    await previewPdf();
  } else {
    setMode("file");
  }
}

await initialize();
